name = "secret-manager"
main = "src/worker.ts"
compatibility_date = "2026-06-01"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "secret-manager"
database_id = "0c37c6cd-de14-4af4-94b6-63aacdc4d2d9"

[vars]
LINK_TTL_MINUTES = "5"
